version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  leo-config-service:
    image: leo/leo-config-service:0.0.1-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/test/docker  || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
  leo-eureka-service:
    image: leo/leo-eureka-service:0.0.1-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      leo-config-service:
        condition: service_healthy
    links:
      - leo-config-service
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SPRING_PROFILES_ACTIVE: docker
  leo-test1-service:
    image: leo/leo-test1-service:0.0.1-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      leo-eureka-service:
        condition: service_healthy
    links:
      - leo-config-service
      - leo-eureka-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  leo-test2-service:
    image: leo/leo-test2-service:0.0.1-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      leo-eureka-service:
        condition: service_healthy
    links:
      - leo-config-service
      - leo-eureka-service
      - leo-test1-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  leo-gateway-service:
    image: leo/leo-gateway-service:0.0.1-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      leo-eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - leo-config-service
      - leo-eureka-service
      - leo-test1-service
      - leo-test2-service
      - zipkin