spring:
  config:
    import: "optional:configserver:http://leo-config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: leo-gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"